// constants/cities.dart
class Cities {
  static const List<String> ukCities = [
    "Aberdeen (AB)",
    "Bath (BA)",
    "Belfast (BT)",
    "Birmingham (B)",
    "Blackburn (BB)",
    "Bolton (BL)",
    "Bournemouth (BH)",
    "Bradford (BD)",
    "Brighton (BN)",
    "Bristol (BS)",
    "Bromley (BR)",
    "Cambridge (CB)",
    "Canterbury (CT)",
    "Cardiff (CF)",
    "Carlisle (CA)",
    "Chelmsford (CM)",
    "Chester (CH)",
    "Colchester (CO)",
    "Coventry (CV)",
    "Crewe (CW)",
    "Croydon (CR)",
    "Darlington (DL)",
    "Dartford (DA)",
    "Derby (DE)",
    "Doncaster (DN)",
    "Dorchester (DT)",
    "Dudley (DY)",
    "Dumfries and Galloway (DG)",
    "Dundee (DD)",
    "Durham (DH)",
    "East Central London (EC)",
    "East London (E)",
    "Edinburgh (EH)",
    "Enfield (EN)",
    "Exeter (EX)",
    "Falkirk (FK)",
    "Fylde (FY)",
    "Glasgow (G)",
    "Gloucester (GL)",
    "Guernsey (GY)",
    "Guildford (GU)",
    "Halifax (HX)",
    "Harrogate (HG)",
    "Harrow (HA)",
    "Hemel Hempstead (HP)",
    "Hereford (HR)",
    "Huddersfield (HD)",
    "Hull (HU)",
    "Ilford and Chigwell (IG)",
    "Inverness (IV)",
    "Ipswich (IP)",
    "Isle of Man (IM)",
    "Jersey (JE)",
    "Kilmarnock (KA)",
    "Kingston upon Thames (KT)",
    "Kirkcaldy (KY)",
    "Kirkwall (KW)",
    "Lancaster (LA)",
    "Leeds (LS)",
    "Leicester (LE)",
    "Lincoln (LN)",
    "Liverpool (L)",
    "Llandrindod Wells (LD)",
    "Llandudno (LL)",
    "Luton (LU)",
    "Manchester (M)",
    "Medway (ME)",
    "Milton Keynes (MK)",
    "Motherwell (ML)",
    "Newcastle (NE)",
    "Newport (NP)",
    "North London (N)",
    "North West London (NW)",
    "Northampton (NN)",
    "Norwich (NR)",
    "Nottingham (NG)",
    "Oldham (OL)",
    "Outer Hebrides (HS)",
    "Oxford (OX)",
    "Paisley (PA)",
    "Perth (PH)",
    "Peterborough (PE)",
    "Plymouth (PL)",
    "Portsmouth (PO)",
    "Preston (PR)",
    "Reading (RG)",
    "Redhill (RH)",
    "Romford (RM)",
    "Salisbury Plain (SP)",
    "Sheffield (S)",
    "Shetland Islands (ZE)",
    "Shrewsbury (SY)",
    "Slough (SL)",
    "South East London (SE)",
    "South West London (SW)",
    "Southampton (SO)",
    "Southend-on-Sea (SS)",
    "St Albans (AL)",
    "Stevenage (SG)",
    "Stockport (SK)",
    "Stoke-on-Trent (ST)",
    "Sunderland (SR)",
    "Sutton (SM)",
    "Swansea (SA)",
    "Swindon (SN)",
    "Taunton (TA)",
    "Tees (TS)",
    "Telford (TF)",
    "Torquay (TQ)",
    "Truro (TR)",
    "Tunbridge Wells (TN)",
    "Tweeddale (TD)",
    "Twickenham (TW)",
    "Uxbridge (UB)",
    "Wakefield (WF)",
    "Walsall (WS)",
    "Warrington (WA)",
    "Watford (WD)",
    "West Central London (WC)",
    "West London (W)",
    "Wigan (WN)",
    "Wolverhampton (WV)",
    "Worcester (WR)",
    "York (YO)"
  ];
}