// # Generated by pub
// # See https://dart.dev/tools/pub/glossary#lockfile
// packages:
// _flutterfire_internals:
// dependency: transitive
// description:
// name: _flutterfire_internals
// sha256: "37a42d06068e2fe3deddb2da079a8c4d105f241225ba27b7122b37e9865fd8f7"
// url: "https://pub.dev"
// source: hosted
// version: "1.3.35"
// animated_checkmark:
// dependency: transitive
// description:
// name: animated_checkmark
// sha256: "878db0c6754c4145e9e17b46f20e304da060ac7a65f8ab4ab43494093f3f8443"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.1"
// archive:
// dependency: transitive
// description:
// name: archive
// sha256: "22600aa1e926be775fa5fe7e6894e7fb3df9efda8891c73f70fb3262399a432d"
// url: "https://pub.dev"
// source: hosted
// version: "3.4.10"
// args:
// dependency: transitive
// description:
// name: args
// sha256: "7cf60b9f0cc88203c5a190b4cd62a99feea42759a7fa695010eb5de1c0b2252a"
// url: "https://pub.dev"
// source: hosted
// version: "2.5.0"
// async:
// dependency: transitive
// description:
// name: async
// sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
// url: "https://pub.dev"
// source: hosted
// version: "2.11.0"
// audioplayers:
// dependency: "direct main"
// description:
// name: audioplayers
// sha256: c05c6147124cd63e725e861335a8b4d57300b80e6e92cea7c145c739223bbaef
// url: "https://pub.dev"
// source: hosted
// version: "5.2.1"
// audioplayers_android:
// dependency: transitive
// description:
// name: audioplayers_android
// sha256: b00e1a0e11365d88576320ec2d8c192bc21f1afb6c0e5995d1c57ae63156acb5
// url: "https://pub.dev"
// source: hosted
// version: "4.0.3"
// audioplayers_darwin:
// dependency: transitive
// description:
// name: audioplayers_darwin
// sha256: "3034e99a6df8d101da0f5082dcca0a2a99db62ab1d4ddb3277bed3f6f81afe08"
// url: "https://pub.dev"
// source: hosted
// version: "5.0.2"
// audioplayers_linux:
// dependency: transitive
// description:
// name: audioplayers_linux
// sha256: "60787e73fefc4d2e0b9c02c69885402177e818e4e27ef087074cf27c02246c9e"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.0"
// audioplayers_platform_interface:
// dependency: transitive
// description:
// name: audioplayers_platform_interface
// sha256: "365c547f1bb9e77d94dd1687903a668d8f7ac3409e48e6e6a3668a1ac2982adb"
// url: "https://pub.dev"
// source: hosted
// version: "6.1.0"
// audioplayers_web:
// dependency: transitive
// description:
// name: audioplayers_web
// sha256: "22cd0173e54d92bd9b2c80b1204eb1eb159ece87475ab58c9788a70ec43c2a62"
// url: "https://pub.dev"
// source: hosted
// version: "4.1.0"
// audioplayers_windows:
// dependency: transitive
// description:
// name: audioplayers_windows
// sha256: "9536812c9103563644ada2ef45ae523806b0745f7a78e89d1b5fb1951de90e1a"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.0"
// autocomplete_textfield:
// dependency: "direct main"
// description:
// name: autocomplete_textfield
// sha256: "8170e66d381c21623f1cfbb957ab9c6b5a45d9c50a6daac7fc57dbc3ba94abb4"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.1"
// basic_utils:
// dependency: "direct main"
// description:
// name: basic_utils
// sha256: "2064b21d3c41ed7654bc82cc476fd65542e04d60059b74d5eed490a4da08fc6c"
// url: "https://pub.dev"
// source: hosted
// version: "5.7.0"
// boolean_selector:
// dependency: transitive
// description:
// name: boolean_selector
// sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.1"
// camera:
// dependency: transitive
// description:
// name: camera
// sha256: "9499cbc2e51d8eb0beadc158b288380037618ce4e30c9acbc4fae1ac3ecb5797"
// url: "https://pub.dev"
// source: hosted
// version: "0.10.5+9"
// camera_android:
// dependency: transitive
// description:
// name: camera_android
// sha256: "7b0aba6398afa8475e2bc9115d976efb49cf8db781e922572d443795c04a4f4f"
// url: "https://pub.dev"
// source: hosted
// version: "0.10.9+1"
// camera_avfoundation:
// dependency: transitive
// description:
// name: camera_avfoundation
// sha256: "5d009ae48de1c8ab621b1c4496dadb6e2a83f3223b76c6e6a4a252414105f561"
// url: "https://pub.dev"
// source: hosted
// version: "0.9.15"
// camera_camera:
// dependency: "direct main"
// description:
// name: camera_camera
// sha256: fd2cffd6a015f588a5fef7e829ad8dff0789ccba0e9faea980d184a13b91e818
// url: "https://pub.dev"
// source: hosted
// version: "3.0.0"
// camera_platform_interface:
// dependency: transitive
// description:
// name: camera_platform_interface
// sha256: a250314a48ea337b35909a4c9d5416a208d736dcb01d0b02c6af122be66660b0
// url: "https://pub.dev"
// source: hosted
// version: "2.7.4"
// camera_web:
// dependency: transitive
// description:
// name: camera_web
// sha256: "9e9aba2fbab77ce2472924196ff8ac4dd8f9126c4f9a3096171cd1d870d6b26c"
// url: "https://pub.dev"
// source: hosted
// version: "0.3.3"
// carousel_slider:
// dependency: "direct main"
// description:
// name: carousel_slider
// sha256: "7b006ec356205054af5beaef62e2221160ea36b90fb70a35e4deacd49d0349ae"
// url: "https://pub.dev"
// source: hosted
// version: "5.0.0"
// change_app_package_name:
// dependency: "direct main"
// description:
// name: change_app_package_name
// sha256: f734e127d334053873733fb61b1ecae73c09abb694b759a4afd26aa9c9547850
// url: "https://pub.dev"
// source: hosted
// version: "1.3.0"
// characters:
// dependency: transitive
// description:
// name: characters
// sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
// url: "https://pub.dev"
// source: hosted
// version: "1.3.0"
// checked_yaml:
// dependency: transitive
// description:
// name: checked_yaml
// sha256: feb6bed21949061731a7a75fc5d2aa727cf160b91af9a3e464c5e3a32e28b5ff
// url: "https://pub.dev"
// source: hosted
// version: "2.0.3"
// chips_choice:
// dependency: "direct main"
// description:
// name: chips_choice
// sha256: ba1c649293cba4e5d827b7f55681390e6c9bb9a98b45cc9128591000fb103d02
// url: "https://pub.dev"
// source: hosted
// version: "3.0.1"
// cli_util:
// dependency: transitive
// description:
// name: cli_util
// sha256: c05b7406fdabc7a49a3929d4af76bcaccbbffcbcdcf185b082e1ae07da323d19
// url: "https://pub.dev"
// source: hosted
// version: "0.4.1"
// clock:
// dependency: transitive
// description:
// name: clock
// sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
// url: "https://pub.dev"
// source: hosted
// version: "1.1.1"
// cloud_firestore:
// dependency: "direct main"
// description:
// name: cloud_firestore
// sha256: a0f161b92610e078b4962d7e6ebeb66dc9cce0ada3514aeee442f68165d78185
// url: "https://pub.dev"
// source: hosted
// version: "4.17.5"
// cloud_firestore_platform_interface:
// dependency: transitive
// description:
// name: cloud_firestore_platform_interface
// sha256: "6a55b319f8d33c307396b9104512e8130a61904528ab7bd8b5402678fca54b81"
// url: "https://pub.dev"
// source: hosted
// version: "6.2.5"
// cloud_firestore_web:
// dependency: transitive
// description:
// name: cloud_firestore_web
// sha256: "89dfa1304d3da48b3039abbb2865e3d30896ef858e569a16804a99f4362283a9"
// url: "https://pub.dev"
// source: hosted
// version: "3.12.5"
// collection:
// dependency: transitive
// description:
// name: collection
// sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
// url: "https://pub.dev"
// source: hosted
// version: "1.18.0"
// connectivity:
// dependency: "direct main"
// description:
// name: connectivity
// sha256: a8e91263cf3e25fb5cc95e19dfde4999e32a648ac3b9e8a558a28165731678f8
// url: "https://pub.dev"
// source: hosted
// version: "3.0.6"
// connectivity_for_web:
// dependency: transitive
// description:
// name: connectivity_for_web
// sha256: "01a390c1d5adc2ed1fa1f52d120c07fe9fd01166a93f965a832fd6cfc0ea6482"
// url: "https://pub.dev"
// source: hosted
// version: "0.4.0+1"
// connectivity_macos:
// dependency: transitive
// description:
// name: connectivity_macos
// sha256: "51ae08d5162eca9669b9d8951ed83ce19c5355a81149f94e4dee2740beb93628"
// url: "https://pub.dev"
// source: hosted
// version: "0.2.1+2"
// connectivity_platform_interface:
// dependency: transitive
// description:
// name: connectivity_platform_interface
// sha256: "2d82e942df9d49f29a24bb07fb5ce085d4a53e47818c62364d2b6deb9e0d7a8e"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.1"
// connectivity_plus:
// dependency: "direct main"
// description:
// name: connectivity_plus
// sha256: "224a77051d52a11fbad53dd57827594d3bd24f945af28bd70bab376d68d437f0"
// url: "https://pub.dev"
// source: hosted
// version: "5.0.2"
// connectivity_plus_platform_interface:
// dependency: transitive
// description:
// name: connectivity_plus_platform_interface
// sha256: cf1d1c28f4416f8c654d7dc3cd638ec586076255d407cef3ddbdaf178272a71a
// url: "https://pub.dev"
// source: hosted
// version: "1.2.4"
// convert:
// dependency: transitive
// description:
// name: convert
// sha256: "0f08b14755d163f6e2134cb58222dd25ea2a2ee8a195e53983d57c075324d592"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.1"
// cool_alert:
// dependency: "direct main"
// description:
// name: cool_alert
// sha256: "080a6c3503a4cded8f626cdead23f17ea40ff066ff50847d71a7a264032ab092"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.1"
// country_code_picker:
// dependency: "direct main"
// description:
// name: country_code_picker
// sha256: "92818885f0e47486539f80463b66f649970506a91dd3c0731ca3ba5308324a4d"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.0"
// country_picker:
// dependency: "direct main"
// description:
// name: country_picker
// sha256: "327f5e15a76352089a6b5057abb761ee5202e7516c9440d8d6a7524139f9b14e"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.26"
// cross_file:
// dependency: transitive
// description:
// name: cross_file
// sha256: "55d7b444feb71301ef6b8838dbc1ae02e63dd48c8773f3810ff53bb1e2945b32"
// url: "https://pub.dev"
// source: hosted
// version: "0.3.4+1"
// crypto:
// dependency: transitive
// description:
// name: crypto
// sha256: ff625774173754681d66daaf4a448684fb04b78f902da9cb3d308c19cc5e8bab
// url: "https://pub.dev"
// source: hosted
// version: "3.0.3"
// csslib:
// dependency: transitive
// description:
// name: csslib
// sha256: "706b5707578e0c1b4b7550f64078f0a0f19dec3f50a178ffae7006b0a9ca58fb"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.0"
// csv:
// dependency: "direct main"
// description:
// name: csv
// sha256: "63ed2871dd6471193dffc52c0e6c76fb86269c00244d244297abbb355c84a86e"
// url: "https://pub.dev"
// source: hosted
// version: "5.1.1"
// cupertino_icons:
// dependency: "direct main"
// description:
// name: cupertino_icons
// sha256: ba631d1c7f7bef6b729a622b7b752645a2d076dba9976925b8f25725a30e1ee6
// url: "https://pub.dev"
// source: hosted
// version: "1.0.8"
// curved_navigation_bar:
// dependency: "direct main"
// description:
// name: curved_navigation_bar
// sha256: bb4ab128fcb6f4a9f0f1f72d227db531818b20218984789777f049fcbf919279
// url: "https://pub.dev"
// source: hosted
// version: "1.0.6"
// date_picker_timeline:
// dependency: "direct main"
// description:
// name: date_picker_timeline
// sha256: dc754de3a99ad654c5633072cb9edac27e0b2875c81c7286e8c6cf419082a110
// url: "https://pub.dev"
// source: hosted
// version: "1.2.5"
// dbus:
// dependency: transitive
// description:
// name: dbus
// sha256: "365c771ac3b0e58845f39ec6deebc76e3276aa9922b0cc60840712094d9047ac"
// url: "https://pub.dev"
// source: hosted
// version: "0.7.10"
// dio:
// dependency: transitive
// description:
// name: dio
// sha256: "11e40df547d418cc0c4900a9318b26304e665da6fa4755399a9ff9efd09034b5"
// url: "https://pub.dev"
// source: hosted
// version: "5.4.3+1"
// dotted_border:
// dependency: "direct main"
// description:
// name: dotted_border
// sha256: "108837e11848ca776c53b30bc870086f84b62ed6e01c503ed976e8f8c7df9c04"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.0"
// equatable:
// dependency: transitive
// description:
// name: equatable
// sha256: c2b87cb7756efdf69892005af546c56c0b5037f54d2a88269b4f347a505e3ca2
// url: "https://pub.dev"
// source: hosted
// version: "2.0.5"
// esys_flutter_share_plus:
// dependency: "direct main"
// description:
// name: esys_flutter_share_plus
// sha256: "622f084679d250db652f26c18f71d7cf4d22054649295b563ad0d636ea3c8df3"
// url: "https://pub.dev"
// source: hosted
// version: "2.2.0"
// excel:
// dependency: "direct main"
// description:
// name: excel
// sha256: f7cde34ffdbb397edeb4566621433bb820517cc0d8676c20d6122a85f749ee49
// url: "https://pub.dev"
// source: hosted
// version: "3.0.0"
// fake_async:
// dependency: transitive
// description:
// name: fake_async
// sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
// url: "https://pub.dev"
// source: hosted
// version: "1.3.1"
// fan_floating_menu:
// dependency: "direct main"
// description:
// name: fan_floating_menu
// sha256: "5681691bf31961342de877de310b670ac503db7a565fd98b0ca1ab767083b8d3"
// url: "https://pub.dev"
// source: hosted
// version: "0.0.1"
// fancy_button_flutter:
// dependency: "direct main"
// description:
// name: fancy_button_flutter
// sha256: "1f85b1e31fe2c67cf3f1c3cb0d9c0a85c78d08b40547ccced6638462476e0d3d"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.3+1"
// ffi:
// dependency: transitive
// description:
// name: ffi
// sha256: "493f37e7df1804778ff3a53bd691d8692ddf69702cf4c1c1096a2e41b4779e21"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.2"
// file:
// dependency: transitive
// description:
// name: file
// sha256: "5fc22d7c25582e38ad9a8515372cd9a93834027aacf1801cf01164dac0ffa08c"
// url: "https://pub.dev"
// source: hosted
// version: "7.0.0"
// file_picker:
// dependency: "direct main"
// description:
// name: file_picker
// sha256: "1bbf65dd997458a08b531042ec3794112a6c39c07c37ff22113d2e7e4f81d4e4"
// url: "https://pub.dev"
// source: hosted
// version: "6.2.1"
// file_selector_linux:
// dependency: transitive
// description:
// name: file_selector_linux
// sha256: "045d372bf19b02aeb69cacf8b4009555fb5f6f0b7ad8016e5f46dd1387ddd492"
// url: "https://pub.dev"
// source: hosted
// version: "0.9.2+1"
// file_selector_macos:
// dependency: transitive
// description:
// name: file_selector_macos
// sha256: b15c3da8bd4908b9918111fa486903f5808e388b8d1c559949f584725a6594d6
// url: "https://pub.dev"
// source: hosted
// version: "0.9.3+3"
// file_selector_platform_interface:
// dependency: transitive
// description:
// name: file_selector_platform_interface
// sha256: a3994c26f10378a039faa11de174d7b78eb8f79e4dd0af2a451410c1a5c3f66b
// url: "https://pub.dev"
// source: hosted
// version: "2.6.2"
// file_selector_windows:
// dependency: transitive
// description:
// name: file_selector_windows
// sha256: d3547240c20cabf205c7c7f01a50ecdbc413755814d6677f3cb366f04abcead0
// url: "https://pub.dev"
// source: hosted
// version: "0.9.3+1"
// firebase_auth:
// dependency: "direct main"
// description:
// name: firebase_auth
// sha256: cfc2d970829202eca09e2896f0a5aa7c87302817ecc0bdfa954f026046bf10ba
// url: "https://pub.dev"
// source: hosted
// version: "4.20.0"
// firebase_auth_platform_interface:
// dependency: transitive
// description:
// name: firebase_auth_platform_interface
// sha256: a0270e1db3b2098a14cb2a2342b3cd2e7e458e0c391b1f64f6f78b14296ec093
// url: "https://pub.dev"
// source: hosted
// version: "7.3.0"
// firebase_auth_web:
// dependency: transitive
// description:
// name: firebase_auth_web
// sha256: "64e067e763c6378b7e774e872f0f59f6812885e43020e25cde08f42e9459837b"
// url: "https://pub.dev"
// source: hosted
// version: "5.12.0"
// firebase_core:
// dependency: "direct main"
// description:
// name: firebase_core
// sha256: "26de145bb9688a90962faec6f838247377b0b0d32cc0abecd9a4e43525fc856c"
// url: "https://pub.dev"
// source: hosted
// version: "2.32.0"
// firebase_core_platform_interface:
// dependency: transitive
// description:
// name: firebase_core_platform_interface
// sha256: e30da58198a6d4b49d5bce4e852f985c32cb10db329ebef9473db2b9f09ce810
// url: "https://pub.dev"
// source: hosted
// version: "5.3.0"
// firebase_core_web:
// dependency: transitive
// description:
// name: firebase_core_web
// sha256: "362e52457ed2b7b180964769c1e04d1e0ea0259fdf7025fdfedd019d4ae2bd88"
// url: "https://pub.dev"
// source: hosted
// version: "2.17.5"
// firebase_messaging:
// dependency: "direct main"
// description:
// name: firebase_messaging
// sha256: a1662cc95d9750a324ad9df349b873360af6f11414902021f130c68ec02267c4
// url: "https://pub.dev"
// source: hosted
// version: "14.9.4"
// firebase_messaging_platform_interface:
// dependency: transitive
// description:
// name: firebase_messaging_platform_interface
// sha256: "87c4a922cb6f811cfb7a889bdbb3622702443c52a0271636cbc90d813ceac147"
// url: "https://pub.dev"
// source: hosted
// version: "4.5.37"
// firebase_messaging_web:
// dependency: transitive
// description:
// name: firebase_messaging_web
// sha256: "0d34dca01a7b103ed7f20138bffbb28eb0e61a677bf9e78a028a932e2c7322d5"
// url: "https://pub.dev"
// source: hosted
// version: "3.8.7"
// fixnum:
// dependency: transitive
// description:
// name: fixnum
// sha256: "25517a4deb0c03aa0f32fd12db525856438902d9c16536311e76cdc57b31d7d1"
// url: "https://pub.dev"
// source: hosted
// version: "1.1.0"
// fl_chart:
// dependency: "direct main"
// description:
// name: fl_chart
// sha256: c1e26c7e48496be85104c16c040950b0436674cdf0737f3f6e95511b2529b592
// url: "https://pub.dev"
// source: hosted
// version: "0.63.0"
// flare_flutter:
// dependency: transitive
// description:
// name: flare_flutter
// sha256: "99d63c60f00fac81249ce6410ee015d7b125c63d8278a30da81edf3317a1f6a0"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.2"
// flexi_chip:
// dependency: transitive
// description:
// name: flexi_chip
// sha256: "5942219bdbd94a7527b69eb5640e6bd05d8ec6a41a5a4a1a10ca22a5a1f41beb"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.8"
// floating_action_bubble_custom:
// dependency: "direct main"
// description:
// name: floating_action_bubble_custom
// sha256: ebd9450380250ad7bb1ea3fc68fb040b3648ca9c5e29c20d0ea878c1e081e0d0
// url: "https://pub.dev"
// source: hosted
// version: "1.0.0+2"
// flutter:
// dependency: "direct main"
// description: flutter
// source: sdk
// version: "0.0.0"
// flutter_datetime_picker_plus:
// dependency: "direct main"
// description:
// name: flutter_datetime_picker_plus
// sha256: "7d82da02c4e070bb28a9107de119ad195e2319b45c786fecc13482a9ffcc51da"
// url: "https://pub.dev"
// source: hosted
// version: "2.2.0"
// flutter_launcher_icons:
// dependency: "direct main"
// description:
// name: flutter_launcher_icons
// sha256: "526faf84284b86a4cb36d20a5e45147747b7563d921373d4ee0559c54fcdbcea"
// url: "https://pub.dev"
// source: hosted
// version: "0.13.1"
// flutter_lints:
// dependency: "direct main"
// description:
// name: flutter_lints
// sha256: a25a15ebbdfc33ab1cd26c63a6ee519df92338a9c10f122adda92938253bef04
// url: "https://pub.dev"
// source: hosted
// version: "2.0.3"
// flutter_local_notifications:
// dependency: "direct main"
// description:
// name: flutter_local_notifications
// sha256: "55b9b229307a10974b26296ff29f2e132256ba4bd74266939118eaefa941cb00"
// url: "https://pub.dev"
// source: hosted
// version: "16.3.3"
// flutter_local_notifications_linux:
// dependency: transitive
// description:
// name: flutter_local_notifications_linux
// sha256: c49bd06165cad9beeb79090b18cd1eb0296f4bf4b23b84426e37dd7c027fc3af
// url: "https://pub.dev"
// source: hosted
// version: "4.0.1"
// flutter_local_notifications_platform_interface:
// dependency: transitive
// description:
// name: flutter_local_notifications_platform_interface
// sha256: "85f8d07fe708c1bdcf45037f2c0109753b26ae077e9d9e899d55971711a4ea66"
// url: "https://pub.dev"
// source: hosted
// version: "7.2.0"
// flutter_phone_direct_caller:
// dependency: "direct main"
// description:
// name: flutter_phone_direct_caller
// sha256: a50abfb49656d39e777278348742d0d09ecfa5d4918bbc4e0b19df46e8dfd858
// url: "https://pub.dev"
// source: hosted
// version: "2.1.1"
// flutter_plugin_android_lifecycle:
// dependency: transitive
// description:
// name: flutter_plugin_android_lifecycle
// sha256: "8cf40eebf5dec866a6d1956ad7b4f7016e6c0cc69847ab946833b7d43743809f"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.19"
// flutter_polyline_points:
// dependency: "direct main"
// description:
// name: flutter_polyline_points
// sha256: "3a1c8c30abee9fb0fbe44c70d5d1cedb10ef28ec7ea285c669f02b3e183483aa"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.0"
// flutter_rating_bar:
// dependency: "direct main"
// description:
// name: flutter_rating_bar
// sha256: d2af03469eac832c591a1eba47c91ecc871fe5708e69967073c043b2d775ed93
// url: "https://pub.dev"
// source: hosted
// version: "4.0.1"
// flutter_ringtone_player:
// dependency: "direct main"
// description:
// name: flutter_ringtone_player
// sha256: d0277a04e629a6582d776f5dcc2a879a733f7326ba073b872a9ccfbff9d9b51f
// url: "https://pub.dev"
// source: hosted
// version: "4.0.0+3"
// flutter_riverpod:
// dependency: "direct main"
// description:
// name: flutter_riverpod
// sha256: "0f1974eff5bbe774bf1d870e406fc6f29e3d6f1c46bd9c58e7172ff68a785d7d"
// url: "https://pub.dev"
// source: hosted
// version: "2.5.1"
// flutter_speed_dial:
// dependency: "direct main"
// description:
// name: flutter_speed_dial
// sha256: "698a037274a66dbae8697c265440e6acb6ab6cae9ac5f95c749e7944d8f28d41"
// url: "https://pub.dev"
// source: hosted
// version: "7.0.0"
// flutter_svg:
// dependency: "direct main"
// description:
// name: flutter_svg
// sha256: "7b4ca6cf3304575fe9c8ec64813c8d02ee41d2afe60bcfe0678bcb5375d596a2"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.10+1"
// flutter_switch:
// dependency: "direct main"
// description:
// name: flutter_switch
// sha256: b91477f926bba135d2d203d7b24367492662d8d9c3aa6adb960b14c1087d3c41
// url: "https://pub.dev"
// source: hosted
// version: "0.3.2"
// flutter_test:
// dependency: "direct dev"
// description: flutter
// source: sdk
// version: "0.0.0"
// flutter_web_plugins:
// dependency: transitive
// description: flutter
// source: sdk
// version: "0.0.0"
// fluttertoast:
// dependency: "direct main"
// description:
// name: fluttertoast
// sha256: "81b68579e23fcbcada2db3d50302813d2371664afe6165bc78148050ab94bf66"
// url: "https://pub.dev"
// source: hosted
// version: "8.2.5"
// font_awesome_flutter:
// dependency: transitive
// description:
// name: font_awesome_flutter
// sha256: "275ff26905134bcb59417cf60ad979136f1f8257f2f449914b2c3e05bbb4cd6f"
// url: "https://pub.dev"
// source: hosted
// version: "10.7.0"
// geocoding:
// dependency: "direct main"
// description:
// name: geocoding
// sha256: "790eea732b22a08dd36fc3761bcd29040461ac20ece4d165264a6c0b5338f115"
// url: "https://pub.dev"
// source: hosted
// version: "2.2.2"
// geocoding_android:
// dependency: transitive
// description:
// name: geocoding_android
// sha256: "4e1539a136c6ab4c44963cfc631970ee499f706a03654fc1d446b2100caf7221"
// url: "https://pub.dev"
// source: hosted
// version: "3.3.0"
// geocoding_ios:
// dependency: transitive
// description:
// name: geocoding_ios
// sha256: "8a39bfb650af55209c42e564036a550b32d029e0733af01dc66c5afea50388d3"
// url: "https://pub.dev"
// source: hosted
// version: "2.3.0"
// geocoding_platform_interface:
// dependency: transitive
// description:
// name: geocoding_platform_interface
// sha256: "8c2c8226e5c276594c2e18bfe88b19110ed770aeb7c1ab50ede570be8b92229b"
// url: "https://pub.dev"
// source: hosted
// version: "3.2.0"
// geolocator:
// dependency: "direct main"
// description:
// name: geolocator
// sha256: f4efb8d3c4cdcad2e226af9661eb1a0dd38c71a9494b22526f9da80ab79520e5
// url: "https://pub.dev"
// source: hosted
// version: "10.1.1"
// geolocator_android:
// dependency: transitive
// description:
// name: geolocator_android
// sha256: f15d1536cd01b1399578f1da1eb5d566e7a718db6a3648f2c24d2e2f859f0692
// url: "https://pub.dev"
// source: hosted
// version: "4.5.4"
// geolocator_apple:
// dependency: transitive
// description:
// name: geolocator_apple
// sha256: bc2aca02423ad429cb0556121f56e60360a2b7d694c8570301d06ea0c00732fd
// url: "https://pub.dev"
// source: hosted
// version: "2.3.7"
// geolocator_platform_interface:
// dependency: transitive
// description:
// name: geolocator_platform_interface
// sha256: "009a21c4bc2761e58dccf07c24f219adaebe0ff707abdfd40b0a763d4003fab9"
// url: "https://pub.dev"
// source: hosted
// version: "4.2.2"
// geolocator_web:
// dependency: transitive
// description:
// name: geolocator_web
// sha256: "102e7da05b48ca6bf0a5bda0010f886b171d1a08059f01bfe02addd0175ebece"
// url: "https://pub.dev"
// source: hosted
// version: "2.2.1"
// geolocator_windows:
// dependency: transitive
// description:
// name: geolocator_windows
// sha256: "53da08937d07c24b0d9952eb57a3b474e29aae2abf9dd717f7e1230995f13f0e"
// url: "https://pub.dev"
// source: hosted
// version: "0.2.3"
// get:
// dependency: "direct main"
// description:
// name: get
// sha256: e4e7335ede17452b391ed3b2ede016545706c01a02292a6c97619705e7d2a85e
// url: "https://pub.dev"
// source: hosted
// version: "4.6.6"
// google_fonts:
// dependency: "direct main"
// description:
// name: google_fonts
// sha256: b1ac0fe2832c9cc95e5e88b57d627c5e68c223b9657f4b96e1487aa9098c7b82
// url: "https://pub.dev"
// source: hosted
// version: "6.2.1"
// google_geocoding_api:
// dependency: "direct main"
// description:
// name: google_geocoding_api
// sha256: "92080e6a0cfcd28b2a73454213e8d0c067342b237392a4431c2787ac10ffeca2"
// url: "https://pub.dev"
// source: hosted
// version: "1.5.2"
// google_maps:
// dependency: transitive
// description:
// name: google_maps
// sha256: "47eef3836b49bb030d5cb3afc60b8451408bf34cf753e571b645d6529eb4251a"
// url: "https://pub.dev"
// source: hosted
// version: "7.1.0"
// google_maps_flutter:
// dependency: "direct main"
// description:
// name: google_maps_flutter
// sha256: "982c2e22ec78d32701bfbd351311e8579a4952035381ac66462c0af11003107b"
// url: "https://pub.dev"
// source: hosted
// version: "2.6.0"
// google_maps_flutter_android:
// dependency: transitive
// description:
// name: google_maps_flutter_android
// sha256: "256b3c974e415bd17555ceff76a5d0badd2cbfd29febfc23070993358f639550"
// url: "https://pub.dev"
// source: hosted
// version: "2.7.0"
// google_maps_flutter_ios:
// dependency: transitive
// description:
// name: google_maps_flutter_ios
// sha256: "6c50bce26ff73079b4401de5bfe77e89d89138897b9dcc6bdfbc7ada842f2bc1"
// url: "https://pub.dev"
// source: hosted
// version: "2.5.2"
// google_maps_flutter_platform_interface:
// dependency: transitive
// description:
// name: google_maps_flutter_platform_interface
// sha256: "167af879da4d004cd58771f1469b91dcc3b9b0a2c5334cc6bf71fd41d4b35403"
// url: "https://pub.dev"
// source: hosted
// version: "2.6.0"
// google_maps_flutter_web:
// dependency: transitive
// description:
// name: google_maps_flutter_web
// sha256: "861c6dd430123e58bb1154342345c5bfa36064120c8ec3dbc0d0b7522add1861"
// url: "https://pub.dev"
// source: hosted
// version: "0.5.6+2"
// html:
// dependency: transitive
// description:
// name: html
// sha256: "3a7812d5bcd2894edf53dfaf8cd640876cf6cef50a8f238745c8b8120ea74d3a"
// url: "https://pub.dev"
// source: hosted
// version: "0.15.4"
// http:
// dependency: "direct main"
// description:
// name: http
// sha256: "761a297c042deedc1ffbb156d6e2af13886bb305c2a343a4d972504cd67dd938"
// url: "https://pub.dev"
// source: hosted
// version: "1.2.1"
// http_parser:
// dependency: "direct main"
// description:
// name: http_parser
// sha256: "2aa08ce0341cc9b354a498388e30986515406668dbcc4f7c950c3e715496693b"
// url: "https://pub.dev"
// source: hosted
// version: "4.0.2"
// image:
// dependency: "direct main"
// description:
// name: image
// sha256: "4c68bfd5ae83e700b5204c1e74451e7bf3cf750e6843c6e158289cf56bda018e"
// url: "https://pub.dev"
// source: hosted
// version: "4.1.7"
// image_gallery_saver:
// dependency: "direct main"
// description:
// name: image_gallery_saver
// sha256: "0aba74216a4d9b0561510cb968015d56b701ba1bd94aace26aacdd8ae5761816"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.3"
// image_picker:
// dependency: "direct main"
// description:
// name: image_picker
// sha256: "1f498d086203360cca099d20ffea2963f48c39ce91bdd8a3b6d4a045786b02c8"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.8"
// image_picker_android:
// dependency: transitive
// description:
// name: image_picker_android
// sha256: "844c6da4e4f2829dffdab97816bca09d0e0977e8dcef7450864aba4e07967a58"
// url: "https://pub.dev"
// source: hosted
// version: "0.8.9+6"
// image_picker_for_web:
// dependency: transitive
// description:
// name: image_picker_for_web
// sha256: "5d6eb13048cd47b60dbf1a5495424dea226c5faf3950e20bf8120a58efb5b5f3"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.4"
// image_picker_ios:
// dependency: transitive
// description:
// name: image_picker_ios
// sha256: "917a5cadd67d052554cfb258595e54217de53fac5b52939426e26319a02e6297"
// url: "https://pub.dev"
// source: hosted
// version: "0.8.9+2"
// image_picker_linux:
// dependency: transitive
// description:
// name: image_picker_linux
// sha256: "4ed1d9bb36f7cd60aa6e6cd479779cc56a4cb4e4de8f49d487b1aaad831300fa"
// url: "https://pub.dev"
// source: hosted
// version: "0.2.1+1"
// image_picker_macos:
// dependency: transitive
// description:
// name: image_picker_macos
// sha256: "3f5ad1e8112a9a6111c46d0b57a7be2286a9a07fc6e1976fdf5be2bd31d4ff62"
// url: "https://pub.dev"
// source: hosted
// version: "0.2.1+1"
// image_picker_platform_interface:
// dependency: transitive
// description:
// name: image_picker_platform_interface
// sha256: "9ec26d410ff46f483c5519c29c02ef0e02e13a543f882b152d4bfd2f06802f80"
// url: "https://pub.dev"
// source: hosted
// version: "2.10.0"
// image_picker_windows:
// dependency: transitive
// description:
// name: image_picker_windows
// sha256: "6ad07afc4eb1bc25f3a01084d28520496c4a3bb0cb13685435838167c9dcedeb"
// url: "https://pub.dev"
// source: hosted
// version: "0.2.1+1"
// intl:
// dependency: "direct main"
// description:
// name: intl
// sha256: "3bc132a9dbce73a7e4a21a17d06e1878839ffbf975568bc875c60537824b0c4d"
// url: "https://pub.dev"
// source: hosted
// version: "0.18.1"
// intl_phone_field:
// dependency: "direct main"
// description:
// name: intl_phone_field
// sha256: "73819d3dfcb68d2c85663606f6842597c3ddf6688ac777f051b17814fe767bbf"
// url: "https://pub.dev"
// source: hosted
// version: "3.2.0"
// js:
// dependency: transitive
// description:
// name: js
// sha256: f2c445dce49627136094980615a031419f7f3eb393237e4ecd97ac15dea343f3
// url: "https://pub.dev"
// source: hosted
// version: "0.6.7"
// js_wrapping:
// dependency: transitive
// description:
// name: js_wrapping
// sha256: e385980f7c76a8c1c9a560dfb623b890975841542471eade630b2871d243851c
// url: "https://pub.dev"
// source: hosted
// version: "0.7.4"
// json_annotation:
// dependency: transitive
// description:
// name: json_annotation
// sha256: b10a7b2ff83d83c777edba3c6a0f97045ddadd56c944e1a23a3fdf43a1bf4467
// url: "https://pub.dev"
// source: hosted
// version: "4.8.1"
// leak_tracker:
// dependency: transitive
// description:
// name: leak_tracker
// sha256: "3f87a60e8c63aecc975dda1ceedbc8f24de75f09e4856ea27daf8958f2f0ce05"
// url: "https://pub.dev"
// source: hosted
// version: "10.0.5"
// leak_tracker_flutter_testing:
// dependency: transitive
// description:
// name: leak_tracker_flutter_testing
// sha256: "932549fb305594d82d7183ecd9fa93463e9914e1b67cacc34bc40906594a1806"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.5"
// leak_tracker_testing:
// dependency: transitive
// description:
// name: leak_tracker_testing
// sha256: "6ba465d5d76e67ddf503e1161d1f4a6bc42306f9d66ca1e8f079a47290fb06d3"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.1"
// lints:
// dependency: transitive
// description:
// name: lints
// sha256: "0a217c6c989d21039f1498c3ed9f3ed71b354e69873f13a8dfc3c9fe76f1b452"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.1"
// lite_rolling_switch:
// dependency: "direct main"
// description:
// name: lite_rolling_switch
// sha256: f5685911d249534ac6ac9862622f18846d31799c90fa4600b475d902d132b090
// url: "https://pub.dev"
// source: hosted
// version: "1.0.1"
// loading_animation_widget:
// dependency: "direct main"
// description:
// name: loading_animation_widget
// sha256: ee3659035528d19145d50cf0107632bf647e7306c88b6a32f35f3bed63f6d728
// url: "https://pub.dev"
// source: hosted
// version: "1.2.1"
// location:
// dependency: "direct main"
// description:
// name: location
// sha256: "06be54f682c9073cbfec3899eb9bc8ed90faa0e17735c9d9fa7fe426f5be1dd1"
// url: "https://pub.dev"
// source: hosted
// version: "5.0.3"
// location_platform_interface:
// dependency: transitive
// description:
// name: location_platform_interface
// sha256: "8aa1d34eeecc979d7c9fe372931d84f6d2ebbd52226a54fe1620de6fdc0753b1"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.2"
// location_web:
// dependency: transitive
// description:
// name: location_web
// sha256: ec484c66e8a4ff1ee5d044c203f4b6b71e3a0556a97b739a5bc9616de672412b
// url: "https://pub.dev"
// source: hosted
// version: "4.2.0"
// logging:
// dependency: transitive
// description:
// name: logging
// sha256: "623a88c9594aa774443aa3eb2d41807a48486b5613e67599fb4c41c0ad47c340"
// url: "https://pub.dev"
// source: hosted
// version: "1.2.0"
// lottie:
// dependency: "direct main"
// description:
// name: lottie
// sha256: a93542cc2d60a7057255405f62252533f8e8956e7e06754955669fd32fb4b216
// url: "https://pub.dev"
// source: hosted
// version: "2.7.0"
// matcher:
// dependency: transitive
// description:
// name: matcher
// sha256: d2323aa2060500f906aa31a895b4030b6da3ebdcc5619d14ce1aada65cd161cb
// url: "https://pub.dev"
// source: hosted
// version: "0.12.16+1"
// material_color_utilities:
// dependency: transitive
// description:
// name: material_color_utilities
// sha256: f7142bb1154231d7ea5f96bc7bde4bda2a0945d2806bb11670e30b850d56bdec
// url: "https://pub.dev"
// source: hosted
// version: "0.11.1"
// meta:
// dependency: transitive
// description:
// name: meta
// sha256: bdb68674043280c3428e9ec998512fb681678676b3c54e773629ffe74419f8c7
// url: "https://pub.dev"
// source: hosted
// version: "1.15.0"
// mime:
// dependency: transitive
// description:
// name: mime
// sha256: "2e123074287cc9fd6c09de8336dae606d1ddb88d9ac47358826db698c176a1f2"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.5"
// multi_image_picker:
// dependency: "direct main"
// description:
// name: multi_image_picker
// sha256: "3071bef51d4165f152bde7e22b6f6769745acd5939d70b9fc3d0c9137dbd0a15"
// url: "https://pub.dev"
// source: hosted
// version: "4.8.01"
// multiple_images_picker:
// dependency: "direct main"
// description:
// name: multiple_images_picker
// sha256: "95f68febbe7ca6b50dbd7edce7345fc70ca0a33f2e82d766b0f79c02b04ff7e4"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.1"
// multiselect_formfield:
// dependency: "direct main"
// description:
// name: multiselect_formfield
// sha256: "3a28c41093a53b4dc30ee0e4f73f67169a8be883dd3b17a4561467185ce1adf8"
// url: "https://pub.dev"
// source: hosted
// version: "0.1.7"
// nested:
// dependency: transitive
// description:
// name: nested
// sha256: "03bac4c528c64c95c722ec99280375a6f2fc708eec17c7b3f07253b626cd2a20"
// url: "https://pub.dev"
// source: hosted
// version: "1.0.0"
// nm:
// dependency: transitive
// description:
// name: nm
// sha256: "2c9aae4127bdc8993206464fcc063611e0e36e72018696cd9631023a31b24254"
// url: "https://pub.dev"
// source: hosted
// version: "0.5.0"
// onboarding:
// dependency: "direct main"
// description:
// name: onboarding
// sha256: "97092ff5852a717549fd5585491b6d5e324ac921722aa010d5a9b0b1a892675d"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.0"
// open_file:
// dependency: "direct main"
// description:
// name: open_file
// sha256: a5a32d44acb7c899987d0999e1e3cbb0a0f1adebbf41ac813ec6d2d8faa0af20
// url: "https://pub.dev"
// source: hosted
// version: "3.3.2"
// path:
// dependency: "direct main"
// description:
// name: path
// sha256: "087ce49c3f0dc39180befefc60fdb4acd8f8620e5682fe2476afd0b3688bb4af"
// url: "https://pub.dev"
// source: hosted
// version: "1.9.0"
// path_drawing:
// dependency: transitive
// description:
// name: path_drawing
// sha256: bbb1934c0cbb03091af082a6389ca2080345291ef07a5fa6d6e078ba8682f977
// url: "https://pub.dev"
// source: hosted
// version: "1.0.1"
// path_parsing:
// dependency: transitive
// description:
// name: path_parsing
// sha256: e3e67b1629e6f7e8100b367d3db6ba6af4b1f0bb80f64db18ef1fbabd2fa9ccf
// url: "https://pub.dev"
// source: hosted
// version: "1.0.1"
// path_provider:
// dependency: "direct main"
// description:
// name: path_provider
// sha256: fec0d61223fba3154d87759e3cc27fe2c8dc498f6386c6d6fc80d1afdd1bf378
// url: "https://pub.dev"
// source: hosted
// version: "2.1.4"
// path_provider_android:
// dependency: transitive
// description:
// name: path_provider_android
// sha256: "6f01f8e37ec30b07bc424b4deabac37cacb1bc7e2e515ad74486039918a37eb7"
// url: "https://pub.dev"
// source: hosted
// version: "2.2.10"
// path_provider_foundation:
// dependency: transitive
// description:
// name: path_provider_foundation
// sha256: f234384a3fdd67f989b4d54a5d73ca2a6c422fa55ae694381ae0f4375cd1ea16
// url: "https://pub.dev"
// source: hosted
// version: "2.4.0"
// path_provider_linux:
// dependency: transitive
// description:
// name: path_provider_linux
// sha256: f7a1fe3a634fe7734c8d3f2766ad746ae2a2884abe22e241a8b301bf5cac3279
// url: "https://pub.dev"
// source: hosted
// version: "2.2.1"
// path_provider_platform_interface:
// dependency: transitive
// description:
// name: path_provider_platform_interface
// sha256: "88f5779f72ba699763fa3a3b06aa4bf6de76c8e5de842cf6f29e2e06476c2334"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.2"
// path_provider_windows:
// dependency: transitive
// description:
// name: path_provider_windows
// sha256: bd6f00dbd873bfb70d0761682da2b3a2c2fccc2b9e84c495821639601d81afe7
// url: "https://pub.dev"
// source: hosted
// version: "2.3.0"
// percent_indicator:
// dependency: "direct main"
// description:
// name: percent_indicator
// sha256: c37099ad833a883c9d71782321cb65c3a848c21b6939b6185f0ff6640d05814c
// url: "https://pub.dev"
// source: hosted
// version: "4.2.3"
// permission_handler:
// dependency: "direct main"
// description:
// name: permission_handler
// sha256: "18bf33f7fefbd812f37e72091a15575e72d5318854877e0e4035a24ac1113ecb"
// url: "https://pub.dev"
// source: hosted
// version: "11.3.1"
// permission_handler_android:
// dependency: transitive
// description:
// name: permission_handler_android
// sha256: "76e4ab092c1b240d31177bb64d2b0bea43f43d0e23541ec866151b9f7b2490fa"
// url: "https://pub.dev"
// source: hosted
// version: "12.0.12"
// permission_handler_apple:
// dependency: transitive
// description:
// name: permission_handler_apple
// sha256: e6f6d73b12438ef13e648c4ae56bd106ec60d17e90a59c4545db6781229082a0
// url: "https://pub.dev"
// source: hosted
// version: "9.4.5"
// permission_handler_html:
// dependency: transitive
// description:
// name: permission_handler_html
// sha256: af26edbbb1f2674af65a8f4b56e1a6f526156bc273d0e65dd8075fab51c78851
// url: "https://pub.dev"
// source: hosted
// version: "0.1.3+2"
// permission_handler_platform_interface:
// dependency: transitive
// description:
// name: permission_handler_platform_interface
// sha256: e9c8eadee926c4532d0305dff94b85bf961f16759c3af791486613152af4b4f9
// url: "https://pub.dev"
// source: hosted
// version: "4.2.3"
// permission_handler_windows:
// dependency: transitive
// description:
// name: permission_handler_windows
// sha256: "1a790728016f79a41216d88672dbc5df30e686e811ad4e698bfc51f76ad91f1e"
// url: "https://pub.dev"
// source: hosted
// version: "0.2.1"
// persistent_bottom_nav_bar:
// dependency: "direct main"
// description:
// name: persistent_bottom_nav_bar
// sha256: e2e031e3366fde01511e372a9a19d720a9b252bb456e5c8d77a30d7a4a2ddfb0
// url: "https://pub.dev"
// source: hosted
// version: "5.0.2"
// petitparser:
// dependency: transitive
// description:
// name: petitparser
// sha256: c15605cd28af66339f8eb6fbe0e541bfe2d1b72d5825efc6598f3e0a31b9ad27
// url: "https://pub.dev"
// source: hosted
// version: "6.0.2"
// pie_chart:
// dependency: "direct main"
// description:
// name: pie_chart
// sha256: "58e6a46999ac938bfa1c3e5be414d6e149f037647197dca03ba3614324c12c82"
// url: "https://pub.dev"
// source: hosted
// version: "5.4.0"
// pinput:
// dependency: "direct main"
// description:
// name: pinput
// sha256: "6d571e38a484f7515a52e89024ef416f11fa6171ac6f32303701374ab9890efa"
// url: "https://pub.dev"
// source: hosted
// version: "4.0.0"
// platform:
// dependency: transitive
// description:
// name: platform
// sha256: "9b71283fc13df574056616011fb138fd3b793ea47cc509c189a6c3fa5f8a1a65"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.5"
// plugin_platform_interface:
// dependency: transitive
// description:
// name: plugin_platform_interface
// sha256: "4820fbfdb9478b1ebae27888254d445073732dae3d6ea81f0b7e06d5dedc3f02"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.8"
// pointycastle:
// dependency: transitive
// description:
// name: pointycastle
// sha256: "70fe966348fe08c34bf929582f1d8247d9d9408130723206472b4687227e4333"
// url: "https://pub.dev"
// source: hosted
// version: "3.8.0"
// pretty_qr_code:
// dependency: "direct main"
// description:
// name: pretty_qr_code
// sha256: cbdb4af29da1c1fa21dd76f809646c591320ab9e435d3b0eab867492d43607d5
// url: "https://pub.dev"
// source: hosted
// version: "3.3.0"
// provider:
// dependency: "direct main"
// description:
// name: provider
// sha256: c8a055ee5ce3fd98d6fc872478b03823ffdb448699c6ebdbbc71d59b596fd48c
// url: "https://pub.dev"
// source: hosted
// version: "6.1.2"
// qr:
// dependency: transitive
// description:
// name: qr
// sha256: "5a1d2586170e172b8a8c8470bbbffd5eb0cd38a66c0d77155ea138d3af3a4445"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.2"
// qr_bar_code_scanner_dialog:
// dependency: "direct main"
// description:
// name: qr_bar_code_scanner_dialog
// sha256: dcb937816d4e562141530265bd1ca39fe00f57000fd79e26c163c957d443e9e4
// url: "https://pub.dev"
// source: hosted
// version: "0.0.5"
// qr_code_scanner:
// dependency: transitive
// description:
// name: qr_code_scanner
// sha256: f23b68d893505a424f0bd2e324ebea71ed88465d572d26bb8d2e78a4749591fd
// url: "https://pub.dev"
// source: hosted
// version: "1.0.1"
// qr_flutter:
// dependency: "direct main"
// description:
// name: qr_flutter
// sha256: "5095f0fc6e3f71d08adef8feccc8cea4f12eec18a2e31c2e8d82cb6019f4b097"
// url: "https://pub.dev"
// source: hosted
// version: "4.1.0"
// riverpod:
// dependency: transitive
// description:
// name: riverpod
// sha256: f21b32ffd26a36555e501b04f4a5dca43ed59e16343f1a30c13632b2351dfa4d
// url: "https://pub.dev"
// source: hosted
// version: "2.5.1"
// sanitize_html:
// dependency: transitive
// description:
// name: sanitize_html
// sha256: "12669c4a913688a26555323fb9cec373d8f9fbe091f2d01c40c723b33caa8989"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.0"
// screenshot:
// dependency: "direct main"
// description:
// name: screenshot
// sha256: d448f43130f49bc7eead1b267b3ea0291cb2450f037bb0a0ecce7aa4c65e2aee
// url: "https://pub.dev"
// source: hosted
// version: "2.5.0"
// share:
// dependency: "direct main"
// description:
// name: share
// sha256: "97e6403f564ed1051a01534c2fc919cb6e40ea55e60a18ec23cee6e0ce19f4be"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.4"
// share_plus:
// dependency: "direct main"
// description:
// name: share_plus
// sha256: "3ef39599b00059db0990ca2e30fca0a29d8b37aae924d60063f8e0184cf20900"
// url: "https://pub.dev"
// source: hosted
// version: "7.2.2"
// share_plus_platform_interface:
// dependency: transitive
// description:
// name: share_plus_platform_interface
// sha256: "251eb156a8b5fa9ce033747d73535bf53911071f8d3b6f4f0b578505ce0d4496"
// url: "https://pub.dev"
// source: hosted
// version: "3.4.0"
// shared_preferences:
// dependency: "direct main"
// description:
// name: shared_preferences
// sha256: "746e5369a43170c25816cc472ee016d3a66bc13fcf430c0bc41ad7b4b2922051"
// url: "https://pub.dev"
// source: hosted
// version: "2.3.2"
// shared_preferences_android:
// dependency: transitive
// description:
// name: shared_preferences_android
// sha256: "480ba4345773f56acda9abf5f50bd966f581dac5d514e5fc4a18c62976bbba7e"
// url: "https://pub.dev"
// source: hosted
// version: "2.3.2"
// shared_preferences_foundation:
// dependency: transitive
// description:
// name: shared_preferences_foundation
// sha256: c4b35f6cb8f63c147312c054ce7c2254c8066745125264f0c88739c417fc9d9f
// url: "https://pub.dev"
// source: hosted
// version: "2.5.2"
// shared_preferences_linux:
// dependency: transitive
// description:
// name: shared_preferences_linux
// sha256: "580abfd40f415611503cae30adf626e6656dfb2f0cee8f465ece7b6defb40f2f"
// url: "https://pub.dev"
// source: hosted
// version: "2.4.1"
// shared_preferences_platform_interface:
// dependency: transitive
// description:
// name: shared_preferences_platform_interface
// sha256: "57cbf196c486bc2cf1f02b85784932c6094376284b3ad5779d1b1c6c6a816b80"
// url: "https://pub.dev"
// source: hosted
// version: "2.4.1"
// shared_preferences_web:
// dependency: transitive
// description:
// name: shared_preferences_web
// sha256: d2ca4132d3946fec2184261726b355836a82c33d7d5b67af32692aff18a4684e
// url: "https://pub.dev"
// source: hosted
// version: "2.4.2"
// shared_preferences_windows:
// dependency: transitive
// description:
// name: shared_preferences_windows
// sha256: "94ef0f72b2d71bc3e700e025db3710911bd51a71cefb65cc609dd0d9a982e3c1"
// url: "https://pub.dev"
// source: hosted
// version: "2.4.1"
// simple_circular_progress_bar:
// dependency: "direct main"
// description:
// name: simple_circular_progress_bar
// sha256: e661ca942fbc617298e975b41fde19003d995de73ca6c2a1526c54d52f07151b
// url: "https://pub.dev"
// source: hosted
// version: "1.0.2"
// simple_gesture_detector:
// dependency: transitive
// description:
// name: simple_gesture_detector
// sha256: ba2cd5af24ff20a0b8d609cec3f40e5b0744d2a71804a2616ae086b9c19d19a3
// url: "https://pub.dev"
// source: hosted
// version: "0.2.1"
// sky_engine:
// dependency: transitive
// description: flutter
// source: sdk
// version: "0.0.99"
// smart_auth:
// dependency: transitive
// description:
// name: smart_auth
// sha256: "88aa8fe66e951c78a307f26d1c29672dce2e9eb3da2e12e853864d0e615a73ad"
// url: "https://pub.dev"
// source: hosted
// version: "2.0.0"
// smooth_page_indicator:
// dependency: "direct main"
// description:
// name: smooth_page_indicator
// sha256: "725bc638d5e79df0c84658e1291449996943f93bacbc2cec49963dbbab48d8ae"
// url: "https://pub.dev"
// source: hosted
// version: "1.1.0"
// source_span:
// dependency: transitive
// description:
// name: source_span
// sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
// url: "https://pub.dev"
// source: hosted
// version: "1.10.0"
// sprintf:
// dependency: transitive
// description:
// name: sprintf
// sha256: "1fc9ffe69d4df602376b52949af107d8f5703b77cda567c4d7d86a0693120f23"
// url: "https://pub.dev"
// source: hosted
// version: "7.0.0"
// stack_trace:
// dependency: transitive
// description:
// name: stack_trace
// sha256: "73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
// url: "https://pub.dev"
// source: hosted
// version: "1.11.1"
// state_notifier:
// dependency: transitive
// description:
// name: state_notifier
// sha256: b8677376aa54f2d7c58280d5a007f9e8774f1968d1fb1c096adcb4792fba29bb
// url: "https://pub.dev"
// source: hosted
// version: "1.0.0"
// stream_channel:
// dependency: transitive
// description:
// name: stream_channel
// sha256: ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7
// url: "https://pub.dev"
// source: hosted
// version: "2.1.2"
// stream_transform:
// dependency: transitive
// description:
// name: stream_transform
// sha256: "14a00e794c7c11aa145a170587321aedce29769c08d7f58b1d141da75e3b1c6f"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.0"
// string_scanner:
// dependency: transitive
// description:
// name: string_scanner
// sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
// url: "https://pub.dev"
// source: hosted
// version: "1.2.0"
// syncfusion_flutter_core:
// dependency: transitive
// description:
// name: syncfusion_flutter_core
// sha256: "7666506885ebc8f62bb928ad4588a73e20caaff2b2cf2b2b56f67d98f4113525"
// url: "https://pub.dev"
// source: hosted
// version: "24.2.9"
// syncfusion_flutter_sliders:
// dependency: "direct main"
// description:
// name: syncfusion_flutter_sliders
// sha256: "54e159dc3cc12c4517ca2b5b0fc78da085edd728adc40c5df949d75fba1af9c2"
// url: "https://pub.dev"
// source: hosted
// version: "24.2.9"
// synchronized:
// dependency: transitive
// description:
// name: synchronized
// sha256: "51b08572b9f091f8c3eb4d9d4be253f196ff0075d5ec9b10a884026d5b55d7bc"
// url: "https://pub.dev"
// source: hosted
// version: "3.3.0+2"
// table_calendar:
// dependency: "direct main"
// description:
// name: table_calendar
// sha256: "1e3521a3e6d3fc7f645a58b135ab663d458ab12504f1ea7f9b4b81d47086c478"
// url: "https://pub.dev"
// source: hosted
// version: "3.0.9"
// term_glyph:
// dependency: transitive
// description:
// name: term_glyph
// sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
// url: "https://pub.dev"
// source: hosted
// version: "1.2.1"
// test_api:
// dependency: transitive
// description:
// name: test_api
// sha256: "5b8a98dafc4d5c4c9c72d8b31ab2b23fc13422348d2997120294d3bac86b4ddb"
// url: "https://pub.dev"
// source: hosted
// version: "0.7.2"
// timezone:
// dependency: transitive
// description:
// name: timezone
// sha256: "2236ec079a174ce07434e89fcd3fcda430025eb7692244139a9cf54fdcf1fc7d"
// url: "https://pub.dev"
// source: hosted
// version: "0.9.4"
// toggle_switch:
// dependency: "direct main"
// description:
// name: toggle_switch
// sha256: dca04512d7c23ed320d6c5ede1211a404f177d54d353bf785b07d15546a86ce5
// url: "https://pub.dev"
// source: hosted
// version: "2.3.0"
// typed_data:
// dependency: transitive
// description:
// name: typed_data
// sha256: facc8d6582f16042dd49f2463ff1bd6e2c9ef9f3d5da3d9b087e244a7b564b3c
// url: "https://pub.dev"
// source: hosted
// version: "1.3.2"
// universal_io:
// dependency: transitive
// description:
// name: universal_io
// sha256: "1722b2dcc462b4b2f3ee7d188dad008b6eb4c40bbd03a3de451d82c78bba9aad"
// url: "https://pub.dev"
// source: hosted
// version: "2.2.2"
// universal_platform:
// dependency: transitive
// description:
// name: universal_platform
// sha256: d315be0f6641898b280ffa34e2ddb14f3d12b1a37882557869646e0cc363d0cc
// url: "https://pub.dev"
// source: hosted
// version: "1.0.0+1"
// url_launcher:
// dependency: "direct main"
// description:
// name: url_launcher
// sha256: "6ce1e04375be4eed30548f10a315826fd933c1e493206eab82eed01f438c8d2e"
// url: "https://pub.dev"
// source: hosted
// version: "6.2.6"
// url_launcher_android:
// dependency: transitive
// description:
// name: url_launcher_android
// sha256: "360a6ed2027f18b73c8d98e159dda67a61b7f2e0f6ec26e86c3ada33b0621775"
// url: "https://pub.dev"
// source: hosted
// version: "6.3.1"
// url_launcher_ios:
// dependency: transitive
// description:
// name: url_launcher_ios
// sha256: "9149d493b075ed740901f3ee844a38a00b33116c7c5c10d7fb27df8987fb51d5"
// url: "https://pub.dev"
// source: hosted
// version: "6.2.5"
// url_launcher_linux:
// dependency: transitive
// description:
// name: url_launcher_linux
// sha256: ab360eb661f8879369acac07b6bb3ff09d9471155357da8443fd5d3cf7363811
// url: "https://pub.dev"
// source: hosted
// version: "3.1.1"
// url_launcher_macos:
// dependency: transitive
// description:
// name: url_launcher_macos
// sha256: b7244901ea3cf489c5335bdacda07264a6e960b1c1b1a9f91e4bc371d9e68234
// url: "https://pub.dev"
// source: hosted
// version: "3.1.0"
// url_launcher_platform_interface:
// dependency: transitive
// description:
// name: url_launcher_platform_interface
// sha256: "552f8a1e663569be95a8190206a38187b531910283c3e982193e4f2733f01029"
// url: "https://pub.dev"
// source: hosted
// version: "2.3.2"
// url_launcher_web:
// dependency: transitive
// description:
// name: url_launcher_web
// sha256: "8d9e750d8c9338601e709cd0885f95825086bd8b642547f26bda435aade95d8a"
// url: "https://pub.dev"
// source: hosted
// version: "2.3.1"
// url_launcher_windows:
// dependency: transitive
// description:
// name: url_launcher_windows
// sha256: ecf9725510600aa2bb6d7ddabe16357691b6d2805f66216a97d1b881e21beff7
// url: "https://pub.dev"
// source: hosted
// version: "3.1.1"
// uuid:
// dependency: transitive
// description:
// name: uuid
// sha256: "814e9e88f21a176ae1359149021870e87f7cddaf633ab678a5d2b0bff7fd1ba8"
// url: "https://pub.dev"
// source: hosted
// version: "4.4.0"
// vector_graphics:
// dependency: transitive
// description:
// name: vector_graphics
// sha256: "32c3c684e02f9bc0afb0ae0aa653337a2fe022e8ab064bcd7ffda27a74e288e3"
// url: "https://pub.dev"
// source: hosted
// version: "1.1.11+1"
// vector_graphics_codec:
// dependency: transitive
// description:
// name: vector_graphics_codec
// sha256: c86987475f162fadff579e7320c7ddda04cd2fdeffbe1129227a85d9ac9e03da
// url: "https://pub.dev"
// source: hosted
// version: "1.1.11+1"
// vector_graphics_compiler:
// dependency: transitive
// description:
// name: vector_graphics_compiler
// sha256: "12faff3f73b1741a36ca7e31b292ddeb629af819ca9efe9953b70bd63fc8cd81"
// url: "https://pub.dev"
// source: hosted
// version: "1.1.11+1"
// vector_math:
// dependency: transitive
// description:
// name: vector_math
// sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
// url: "https://pub.dev"
// source: hosted
// version: "2.1.4"
// vm_service:
// dependency: transitive
// description:
// name: vm_service
// sha256: "5c5f338a667b4c644744b661f309fb8080bb94b18a7e91ef1dbd343bed00ed6d"
// url: "https://pub.dev"
// source: hosted
// version: "14.2.5"
// web:
// dependency: transitive
// description:
// name: web
// sha256: "97da13628db363c635202ad97068d47c5b8aa555808e7a9411963c533b449b27"
// url: "https://pub.dev"
// source: hosted
// version: "0.5.1"
// widget_event:
// dependency: transitive
// description:
// name: widget_event
// sha256: "16127872166dabc55b9180f039fdfb4e78edf5db4936cc43c3b5ab6d66b7836c"
// url: "https://pub.dev"
// source: hosted
// version: "1.3.3"
// win32:
// dependency: "direct main"
// description:
// name: win32
// sha256: "0a989dc7ca2bb51eac91e8fd00851297cfffd641aa7538b165c62637ca0eaa4a"
// url: "https://pub.dev"
// source: hosted
// version: "5.4.0"
// xdg_directories:
// dependency: transitive
// description:
// name: xdg_directories
// sha256: faea9dee56b520b55a566385b84f2e8de55e7496104adada9962e0bd11bcff1d
// url: "https://pub.dev"
// source: hosted
// version: "1.0.4"
// xml:
// dependency: transitive
// description:
// name: xml
// sha256: b015a8ad1c488f66851d762d3090a21c600e479dc75e68328c52774040cf9226
// url: "https://pub.dev"
// source: hosted
// version: "6.5.0"
// yaml:
// dependency: transitive
// description:
// name: yaml
// sha256: "75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
// url: "https://pub.dev"
// source: hosted
// version: "3.1.2"
// sdks:
// dart: ">=3.5.0 <4.0.0"
// flutter: ">=3.22.0"
